/**
 * Core TypeScript type definitions for AI Spend Audit — Day 2.
 * Extended with new tools (Windsurf, Anthropic API) and richer recommendation shape.
 */

// --- Supported AI Tools (expanded from Day 1) ---
export type AITool =
  | "ChatGPT"
  | "Claude"
  | "Cursor"
  | "GitHub Copilot"
  | "Gemini"
  | "OpenAI API"
  | "Anthropic API"
  | "Windsurf";

// --- Plan options per tool ---
export type ChatGPTPlan = "Free" | "Plus" | "Team" | "Enterprise";
export type ClaudePlan = "Free" | "Pro" | "Team" | "Enterprise";
export type CursorPlan = "Hobby" | "Pro" | "Business";
export type GitHubCopilotPlan = "Individual" | "Business" | "Enterprise";
export type GeminiPlan = "Free" | "Advanced" | "Business" | "Enterprise";
export type OpenAIAPIPlan = "Pay-as-you-go" | "Committed Use";
export type AnthropicAPIPlan = "Pay-as-you-go" | "Committed Use";
export type WindsurfPlan = "Free" | "Pro" | "Teams";

export type AIPlan =
  | ChatGPTPlan
  | ClaudePlan
  | CursorPlan
  | GitHubCopilotPlan
  | GeminiPlan
  | OpenAIAPIPlan
  | AnthropicAPIPlan
  | WindsurfPlan;

// --- Primary use cases ---
export type UseCase =
  | "coding"
  | "writing"
  | "research"
  | "data"
  | "mixed";

// --- A single tool entry in the audit form ---
export interface AuditToolEntry {
  id: string;
  tool: AITool;
  plan: AIPlan;
  monthlySpend: number;
  seats: number;
  teamSize: number;
  useCase: UseCase;
}

// --- Recommendation generated by the audit engine ---
export interface AuditRecommendation {
  toolId: string;
  tool: AITool;
  currentPlan: AIPlan;
  recommendedPlan: AIPlan | null;
  currentMonthlySpend: number;
  optimizedMonthlySpend: number;
  monthlySavings: number;
  yearlySavings: number;
  reason: string;
  savingsPercent: number;
  priority: "high" | "medium" | "low" | "none";
  /** 0–100 confidence in the recommendation */
  confidenceScore: number;
  /** Short action label for the UI */
  actionLabel: string;
}

// --- Full audit result ---
export interface AuditResult {
  recommendations: AuditRecommendation[];
  totalMonthlySpend: number;
  totalOptimizedMonthlySpend: number;
  totalMonthlySavings: number;
  totalYearlySavings: number;
  overallSavingsPercent: number;
  generatedAt: string; // ISO timestamp
}

// --- AI-generated summary ---
export interface AuditSummary {
  text: string;
  generatedByAI: boolean;
  model?: string;
}

// --- Form data shape used in the audit form ---
export interface ToolFormData {
  tool: AITool;
  plan: AIPlan;
  monthlySpend: number;
  seats: number;
  teamSize: number;
  useCase: UseCase;
}
