/**
 * Core TypeScript type definitions for AI Spend Audit.
 * These types are shared across the entire application.
 */

// --- Supported AI Tools ---
export type AITool =
  | "ChatGPT"
  | "Claude"
  | "Cursor"
  | "GitHub Copilot"
  | "Gemini"
  | "OpenAI API";

// --- Plan options per tool ---
export type ChatGPTPlan = "Free" | "Plus" | "Team" | "Enterprise";
export type ClaudePlan = "Free" | "Pro" | "Team" | "Enterprise";
export type CursorPlan = "Hobby" | "Pro" | "Business";
export type GitHubCopilotPlan = "Individual" | "Business" | "Enterprise";
export type GeminiPlan = "Free" | "Advanced" | "Business" | "Enterprise";
export type OpenAIAPIPlan = "Pay-as-you-go" | "Committed Use";

export type AIPlan =
  | ChatGPTPlan
  | ClaudePlan
  | CursorPlan
  | GitHubCopilotPlan
  | GeminiPlan
  | OpenAIAPIPlan;

// --- Use cases ---
export type UseCase =
  | "Coding"
  | "Writing"
  | "Research"
  | "Customer Support"
  | "Data Analysis"
  | "General Productivity"
  | "Other";

// --- A single tool entry in the audit form ---
export interface AuditToolEntry {
  id: string; // uuid for React key
  tool: AITool;
  plan: AIPlan;
  monthlySpend: number;
  seats: number;
  useCase: UseCase;
}

// --- Recommendation generated by the audit engine ---
export interface AuditRecommendation {
  toolId: string;
  tool: AITool;
  currentPlan: AIPlan;
  recommendedPlan: AIPlan | null;
  currentMonthlySpend: number;
  optimizedMonthlySpend: number;
  monthlySavings: number;
  yearlySavings: number;
  reason: string;
  savingsPercent: number;
  priority: "high" | "medium" | "low" | "none";
}

// --- Full audit result ---
export interface AuditResult {
  recommendations: AuditRecommendation[];
  totalMonthlySpend: number;
  totalOptimizedMonthlySpend: number;
  totalMonthlySavings: number;
  totalYearlySavings: number;
  overallSavingsPercent: number;
  generatedAt: string; // ISO timestamp
}

// --- Form data shape matching AuditToolEntry without id ---
export interface ToolFormData {
  tool: AITool;
  plan: AIPlan;
  monthlySpend: number;
  seats: number;
  useCase: UseCase;
}
